name: Build ROM

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build_agbcc:
    name: Build ROM with agbcc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: sudo apt-get install binutils-arm-none-eabi gcc-arm-none-eabi
      - name: Build & install agbcc
        run: |
          cd ..
          git clone --depth 1 https://github.com/pret/agbcc
          cd agbcc
          ./build.sh
          ./install.sh ../Moemon_Emerald
      - name: Build ROM
        run: |
          make -j$(nproc) debug=1

  build_modern:
    name: Build ROM with DevKitPro
    runs-on: ubuntu-latest
    container: devkitpro/devkitarm
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          apt update
          apt install -y build-essential libpng-dev
      - name: Build ROM
        run: |
          make -j$(nproc) modern debug=1
